### ISSUE TITLE
想问下data_path 中的48/all_data是什么

### ISSUE THREAD

**Issue by ZhikangNiu** [yeyupiaoling/Pytorch-MTCNN#4]
![image](https://user-images.githubusercontent.com/73390819/128104272-3983a6d9-49eb-4ca9-9f0a-6c813be20eea.png)
w
这是我的dataset组织方式，不知道对不对

**Comment by ZhikangNiu** [comment]
可能不是太懂那个.header是什么意思，谢谢

**Comment by yeyupiaoling** [comment]
@NoFish-528 应该是没问题的，all_data是把图片全部打包成一个二进制文件，.header是用于分割文件
