### ISSUE TITLE
处理Onet的数据的时候，显示gpu内存不足了，前两个模型处理数据时候没有问题，这个正常嘛，我的是1050 Ti。

### ISSUE THREAD

**Issue by aidiaoyudemao** [yeyupiaoling/Pytorch-MTCNN#5]

**Comment by yeyupiaoling** [comment]
你的显卡显存多少，这个不需要很多显存的、

**Comment by aidiaoyudemao** [comment]
我的显卡是1050ti 4G

在 2022-02-07 18:23:16，"夜雨飘零" ***@***.***> 写道：


你的显卡显存多少，这个不需要很多显存的、

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aidiaoyudemao** [comment]
错误就是out of memory，请分配1.45G之类的话，我搜索了，这个错误情况，猜测是电脑4G 
 gpu有点小，请问一下，你的是多大的

在 2022-02-07 18:23:16，"夜雨飘零" ***@***.***> 写道：


你的显卡显存多少，这个不需要很多显存的、

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yeyupiaoling** [comment]
我的8G

**Comment by aidiaoyudemao** [comment]
嗯嗯  那可能是因为我的有点小了 谢谢

在 2022-02-11 20:01:43，"夜雨飘零" ***@***.***> 写道：


我的8G

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aidiaoyudemao** [comment]
请问有Onet需要的，处理好的数据嘛？如果有的话希望可以分享一下，谢谢










At 2022-02-11 20:01:43, "夜雨飘零" ***@***.***> wrote:

我的8G

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yeyupiaoling** [comment]
很久的项目，数据早就删除了。

**Comment by aidiaoyudemao** [comment]
好的，谢谢

在 2022-02-12 22:28:25，"夜雨飘零" ***@***.***> 写道：


很久的项目，数据早就删除了。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aidiaoyudemao** [comment]
请问，您的这个项目，是没有对模型进行测试吗，准确率可以达到了多少呢？

在 2022-02-12 22:28:25，"夜雨飘零" ***@***.***> 写道：


很久的项目，数据早就删除了。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yeyupiaoling** [comment]
没有哦，做输出训练的loss
